
CREATE TABLE IF NOT EXISTS bot (
    ID INTEGER NOT NULL,
    DefaultGame VARCHAR(512),
    DefaultPrefix VARCHAR(32),
    Permissions INTEGER NOT NULL DEFAULT 0,
    UserName VARCHAR(256),
    PRIMARY KEY (ID)
);

INSERT INTO bot
SELECT * FROM (SELECT 0, 'DEFAULT', 'z.', 0, 'sp.z')
WHERE NOT EXISTS (
    SELECT ID FROM bot WHERE ID = 0
) LIMIT 1;

CREATE TABLE IF NOT EXISTS servers (
    ID INTEGER NOT NULL,
    DisplayName VARCHAR(2048) NOT NULL,
    TwitchChannel INTEGER NOT NULL DEFAULT 0,
    ActivityLogChannel INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS moderators (
    ID INTEGER NOT NULL,
    ServerID INTEGER NOT NULL,
	Owner BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (ID),
    FOREIGN KEY (ServerID) REFERENCES servers(ID)
);

CREATE TABLE IF NOT EXISTS twitchchannels (
    ID INTEGER NOT NULL,
    Name VARCHAR(64) NOT NULL,
    LastUpdate TIMESTAMP NOT NULL,
    ServerID INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ServerID) REFERENCES servers(ID)
);

CREATE TABLE IF NOT EXISTS timeouts (
    ID INTEGER NOT NULL,
    ServerID INTEGER NOT NULL,
    MemberID INTEGER NOT NULL,
    TimeoutTime TIMESTAMP NOT NULL,
    TimeInMinutes INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ServerID) REFERENCES servers(ID)
);

CREATE TABLE IF NOT EXISTS users (
    ID INTEGER NOT NULL,
    TimeoutCount INTEGER NOT NULL DEFAULT 0
)